dist: xenial

language: c

env:
    global:
        - CACHE_ENABLE=true

os: linux

# Build on both Clang and GCC
compiler:
    - clang
    - gcc

addons:
    apt:
        packages:
            - cmake
            - libxcb-randr0-dev
            - libxcb-keysyms1-dev
            - libxcb-ewmh-dev
            - libxcb-icccm4-dev

cache:
    apt: true
    ccache: true
    directories:
        - "$TRAVIS_BUILD_DIR/.cache/dep-dl"

script:
    - mkdir build; cd build
    - cmake ../
    - make
    - ctest
