language: c

# Build on both Linux and OSX
os:
    - linux
    - osx

compiler:
    - clang
    - gcc

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y update ; fi

install:
    - ./.travis/install.sh

script:
    - mkdir build; cd build
    - cmake ../
    - make
    - make test
