dist: xenial

osx_image: xcode10.1

language: c

env:
    global:
        - CACHE_ENABLE=true

# Build on both Linux and Darwin
os:
    - linux
    - osx

# Build on both Clang and GCC
compiler:
    - clang
    - gcc

addons:
    apt:
        packages:
            - cmake
            - libxcb-randr0-dev
            - libxcb-keysyms1-dev
            - libxcb-ewmh-dev
            - libxcb-icccm4-dev
    homebrew:
        update: true
        taps: caskroom/cask
        packages:
            - cmake
        casks:
            - xquartz

cache:
    apt: true
    ccache: true
    directories:
        - "$TRAVIS_BUILD_DIR/.cache/dep-dl"
        - "$HOME/Library/Caches/Homebrew"

install:
    - ./ci/install.sh

script:
    - mkdir build; cd build
    - cmake ../
    - make
