dist: xenial

language: c

env:
    global:
        - CACHE_ENABLE=true

os: linux

# Build on both Clang and GCC
compiler:
    - clang
    - gcc

addons:
    apt:
        packages:
            - cmake
            - libxcb-randr0-dev
            - libxcb-xinerama0-dev
            - libxcb-keysyms1-dev
            - libxcb-ewmh-dev
            - libxcb-icccm4-dev
            - libxcb-util-dev

cache:
    apt: true
    ccache: true

script:
    - mkdir build; cd build
    - cmake -D ENABLE_TESTING=ON ../
    - make
    - make check
