dist: xenial

osx_image: xcode10.1

language: c

env:
    global:
        - CACHE_ENABLE=true

# Build on both Linux and Darwin
os:
    - linux
    - osx

# Build on both Clang and GCC
compiler:
    - clang
    - gcc

addons:
    apt:
        packages:
            - cmake
    homebrew:
        update: true
        packages:
            - cmake

cache:
    apt: true
    ccache: true
    directories:
        - "$TRAVIS_BUILD_DIR/.cache/dep-dl"

install:
    - ./ci/install.sh

script:
    - mkdir build; cd build
    - cmake ../
    - make
